// GENERATED by scripts/slice-encounters.py — do not edit.
// Every enemy sprite, background and foreground the slicer produced.
// The admin pickers read this because a browser cannot list a directory.
export const ENEMY_SPRITES: Record<string, string[]> = {
  "barbies": ["barbies-01", "barbies-02", "barbies-03", "barbies-04", "barbies-05", "barbies-06", "barbies-07", "barbies-08", "barbies-09", "barbies-10", "barbies-11", "barbies-12"],
  "cops": ["cops-01", "cops-02", "cops-03", "cops-04", "cops-05", "cops-06", "cops-07", "cops-08", "cops-09", "cops-10"],
  "cops-boss": ["cops-boss-01"],
  "heroic-guards": ["heroic-guards-01", "heroic-guards-02", "heroic-guards-03", "heroic-guards-04", "heroic-guards-05", "heroic-guards-06", "heroic-guards-07", "heroic-guards-08", "heroic-guards-09", "heroic-guards-10", "heroic-guards-11", "heroic-guards-12", "heroic-guards-13", "heroic-guards-14", "heroic-guards-15", "heroic-guards-16"],
  "king-boss": ["king-boss-01"],
  "lady-boss": ["lady-boss-01"],
  "lady-boss-2": ["lady-boss-2-01"],
  "monk-boss": ["monk-boss-01"],
  "monk-boss-hq": ["monk-boss-hq-01"],
  "monks": ["monks-01", "monks-02", "monks-03", "monks-04", "monks-05", "monks-06", "monks-07", "monks-08", "monks-09", "monks-10"],
  "sister-boss": ["sister-boss-01"],
  "villagers": ["villagers-01", "villagers-02", "villagers-03", "villagers-04", "villagers-05", "villagers-06", "villagers-07", "villagers-08", "villagers-09", "villagers-10", "villagers-11", "villagers-12", "villagers-13", "villagers-14", "villagers-15", "villagers-16"],
};

export const BACKGROUNDS: string[] = ["barbies", "cops", "guards", "guards-2", "monks", "poors"];
export const FOREGROUNDS: string[] = [];
