// GENERATED by scripts/slice-sheets.py — do not edit.
// Every sprite the slicer produced, by folder. The admin picker reads
// this because a browser cannot list a directory.
export const SPRITE_INDEX: Record<string, string[]> = {
  "body": ["female-brown", "female-dark", "female-fair", "female-light", "female-tan", "male-brown", "male-dark", "male-fair", "male-light", "male-tan"],
  "chest": ["female-t1", "female-t2", "female-t3", "female-t4", "female-t5", "male-t1", "male-t2", "male-t3", "male-t4", "male-t5"],
  "enemies": ["_contact-barbies", "_contact-cops", "_contact-heroic-guards", "_contact-monks", "_contact-villagers"],
  "face": ["face01", "face02", "face03", "face04", "face05", "face06", "face07", "face08", "face09", "face10", "face11", "face12", "face13", "face14", "face15", "face16", "face17", "face18", "face19", "face20", "face21", "face22", "face23", "face24", "face25", "face26", "face27", "face28", "face29", "face30", "face31", "face32", "face33", "face34", "face35", "face36", "face37", "face38", "face39", "face40", "face41", "face42", "face43", "face44", "face45", "face46", "face47"],
  "hair": ["s01-blonde", "s01-brown", "s01-red", "s01-violet", "s02-blonde", "s02-brown", "s02-red", "s02-violet", "s03-blonde", "s03-brown", "s03-red", "s03-violet", "s04-blonde", "s04-brown", "s04-red", "s04-violet", "s05-blonde", "s05-brown", "s05-red", "s05-violet", "s06-blonde", "s06-brown", "s06-red", "s06-violet", "s07-blonde", "s07-brown", "s07-red", "s07-violet", "s08-blonde", "s08-brown", "s08-red", "s08-violet", "s09-blonde", "s09-brown", "s09-red", "s09-violet", "s10-blonde", "s10-brown", "s10-red", "s10-violet"],
  "hand": ["female-brown", "female-dark", "female-fair", "female-light", "female-tan", "male-brown", "male-dark", "male-fair", "male-light", "male-tan"],
  "head": ["head01", "head02", "head03", "head04", "head05", "head06", "head07", "head08", "head09", "head10", "head11", "head12", "head13", "head14", "head15", "head16", "head17", "head18", "head19", "head20", "head21", "head22", "head23", "head24"],
  "mainhand": ["mh01", "mh02", "mh03", "mh04", "mh05", "mh06", "mh07", "mh08", "mh09", "mh10", "mh11", "mh12", "mh13", "mh14", "mh15", "mh16", "mh17", "mh18", "mh19", "mh20", "mh21", "mh22", "mh23", "mh24", "mh25", "mh26", "mh27", "mh28"],
  "offhand": ["oh01", "oh02", "oh03", "oh04", "oh05", "oh06", "oh07", "oh08", "oh09", "oh10"],
  "pants": ["female-t1", "female-t2", "female-t3", "female-t4", "female-t5", "male-t1", "male-t2", "male-t3", "male-t4", "male-t5"],
};
