/**
 * The loadout's backend: read your character, and change it.
 *
 * Runs on Supabase Edge Functions (Deno). This is the only piece of the game
 * that is hosted — the game server, the overlay and the admin panel all live
 * on the streamer's PC. See DEPLOY.md.
 *
 * WHY A FUNCTION AND NOT DIRECT DATABASE WRITES
 * ---------------------------------------------
 * Row level security decides WHICH ROWS a viewer may touch. It cannot decide
 * whether the values in them are legal. A viewer with an insert policy could
 * set their own `unspentPoints` to 999, or equip a legendary they never
 * looted, and Postgres would be right to allow it — nothing in a row-level
 * policy knows what a gear requirement is.
 *
 * So reads go through RLS (`select` on your own row) and every WRITE comes
 * here, where the actual `GameEngine` applies the actual command with the
 * actual content. The rules exist once, in TypeScript, and the loadout cannot
 * drift from the game.
 *
 * WHY THE ENGINE RUNS HERE AT ALL. The alternative was re-implementing
 * requirements, prices and point costs in SQL — the same rules written twice,
 * wrong within a month, and wrong in the direction that favours whoever
 * notices first. The engine is pure TypeScript whose only Node import is
 * `node:events`, which Deno provides.
 */
// Both generated by `npm run bundle:edge` — see scripts/bundle-edge-content.ts
// for why the engine is bundled rather than imported from source.
import { ContentRegistry, GameEngine, memberPower } from "./_engine.js";
import type { Character, GameCommand, Role } from "./_engine.js";
import bundledContent from "./_content.json" with { type: "json" };

/**
 * What a viewer may do to their own character.
 *
 * An allowlist, not a denylist. Anything not named here is refused, so a
 * command added to the union later cannot reach this endpoint by being
 * forgotten — the failure mode of the opposite arrangement is `grant_gear`
 * quietly becoming callable from a phone.
 */
const ALLOWED = new Set<GameCommand["type"]>([
  "ensure_character",
  "equip_gear",
  "unequip_gear",
  "allocate_points",
  "respec",
  "set_role",
  "set_appearance",
  "recycle_gear",
  // Mints nothing: the item was rolled when the fight resolved and this only
  // moves it from a sealed chest into the bag. Safe from a phone in a way
  // `grant_gear` is not, which is the line this allowlist exists to draw.
  "open_chest",
  "buy_gear",
  "buy_consumable",
  "use_consumable",
]);

// Built once per isolate, not per request: parsing and validating 119 gear
// definitions on every click would dominate the response time.
const content = new ContentRegistry();
content.loadObjects(bundledContent as Parameters<ContentRegistry["loadObjects"]>[0]);

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
/**
 * Injected by the platform — nothing sets this by hand.
 *
 * `SUPABASE_SERVICE_ROLE_KEY` is the LEGACY name and is still injected, so
 * this keeps working. Supabase is retiring the anon / service_role JWTs by
 * the end of 2026; the replacement is `SUPABASE_SECRET_KEYS` (plural — a
 * project may hold several). Switch when the legacy pair is actually
 * disabled, not before: a function that reads the new variable on a project
 * still issuing the old keys gets `undefined` and fails on the first write.
 */
const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json" },
  });

/**
 * LOADOUT_ORIGIN, as a comma-separated ALLOWLIST rather than one origin.
 *
 * The loadout is served from a different origin to the function, so this is
 * load-bearing rather than boilerplate — and a credentialed request cannot
 * use `*`, so the header has to name one exact origin per response. With a
 * single configured value that meant redeploying the secret every time you
 * moved between `dev:web` on :5173, the built page the game server serves on
 * :8787, and the hosted domain.
 *
 * So: configure several, echo back whichever one asked, if it is on the list.
 * `Vary: Origin` is what stops a cache handing one origin's response to
 * another. This mirrors ALLOWED_ORIGINS on the game server (src/server/
 * auth.ts) deliberately — one idea, spelled the same way in both places.
 *
 * An unrecognised origin gets no CORS header at all, which the browser turns
 * into the block it should be.
 */
function cors(req?: Request): Record<string, string> {
  const allowed = (Deno.env.get("LOADOUT_ORIGIN") ?? "")
    .split(",")
    .map((o) => o.trim().replace(/\/$/, ""))
    .filter(Boolean);
  const asked = (req?.headers.get("Origin") ?? "").replace(/\/$/, "");
  // One entry and no Origin header is the ordinary server-to-server case;
  // fall back to the single configured value so nothing regresses.
  const origin = asked && allowed.includes(asked) ? asked : (allowed.length === 1 ? allowed[0]! : "");
  return {
    "Access-Control-Allow-Origin": origin,
    // `apikey` is NOT optional here, and leaving it out is a silent break:
    // supabase-js sends it on every call (see callCharacterFn), so the
    // browser's preflight asks for it, and a preflight that does not list it
    // fails before the real request is ever made. The symptom is a loadout
    // stuck on "Loading character…" with a CORS error in the console and a
    // function that never sees a request at all.
    //
    // `x-client-info` is sent by supabase-js itself on some paths, for the
    // same reason it is listed here.
    "Access-Control-Allow-Headers": "authorization, content-type, apikey, x-client-info",
    "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
    Vary: "Origin",
  };
}

/** PostgREST, with the service key. Bypasses RLS by design — see the file note. */
async function db(path: string, init: RequestInit = {}): Promise<Response> {
  const res = await fetch(`${SUPABASE_URL}/rest/v1${path}`, {
    ...init,
    headers: {
      apikey: SERVICE_KEY,
      Authorization: `Bearer ${SERVICE_KEY}`,
      "Content-Type": "application/json",
      ...((init.headers as Record<string, string>) ?? {}),
    },
  });
  if (!res.ok) throw new Error(`db ${init.method ?? "GET"} ${path}: ${res.status} ${await res.text()}`);
  return res;
}

/**
 * The Twitch id of whoever is calling, from their verified JWT.
 *
 * The token is verified by the platform before this function runs (leave
 * `verify_jwt` on), so the claims can be trusted — but the id is read from the
 * TOKEN and never from the request body. That is the same rule the game server
 * follows for `requestedBy`, and for the same reason: a field the caller can
 * type is a field the caller can lie in.
 */
function callerTwitchId(req: Request): string | null {
  const auth = req.headers.get("Authorization");
  if (!auth?.startsWith("Bearer ")) return null;
  try {
    const payload = JSON.parse(atob(auth.slice(7).split(".")[1]!));
    const id = payload?.user_metadata?.provider_id ?? payload?.user_metadata?.sub;
    return typeof id === "string" && id ? id : null;
  } catch {
    return null;
  }
}

interface Row {
  id: string;
  data: Character;
  in_run: boolean;
}

async function loadRow(viewerId: string): Promise<Row | null> {
  const res = await db(`/characters?id=eq.${encodeURIComponent(viewerId)}&select=id,data,in_run`);
  const rows = (await res.json()) as Row[];
  return rows[0] ?? null;
}

/**
 * CORS is applied HERE, on the way out, rather than by each `json()` call.
 *
 * The header depends on the REQUEST (which origin asked), and `json` is
 * module-scoped with a dozen call sites that would each have to thread `req`
 * through to reach it. Threading it is the version of this that compiles and
 * then quietly misses one return path; wrapping the handler cannot miss one.
 *
 * A module-level "current request" would be the other tempting shortcut and
 * is worse: Deno.serve handles requests concurrently, so it is a race.
 */
Deno.serve(async (req: Request) => {
  const headers = cors(req);
  const response = await handle(req);
  for (const [k, v] of Object.entries(headers)) {
    // Skip an empty Allow-Origin: an unlisted origin should get no header at
    // all, which is what the browser turns into a block.
    if (v) response.headers.set(k, v);
  }
  return response;
});

async function handle(req: Request): Promise<Response> {
  if (req.method === "OPTIONS") return new Response(null, { status: 204 });

  const twitchId = callerTwitchId(req);
  if (!twitchId) return json({ ok: false, message: "Not signed in" }, 401);
  const viewerId = `twitch:${twitchId}`;

  try {
    const row = await loadRow(viewerId);

    // The standings. Here rather than on the game server because the loadout
    // is hosted and the game server is on the streamer's PC — a viewer opening
    // the board from a phone has no way to reach it.
    //
    // Corruption is COMPUTED rather than stored in a column. It is a function
    // of level, spent points and worn gear against the current balance, so a
    // stored copy would be one balance change away from being wrong, and
    // recomputing a hundred characters is milliseconds.
    if (req.method === "GET" && new URL(req.url).searchParams.has("board")) {
      const res = await db("/characters?select=data&limit=500");
      const rows = (await res.json()) as { data: Character }[];
      const standings = rows
        .map((r) => ({
          name: r.data.name,
          level: r.data.level,
          role: r.data.role as Role,
          corruption: memberPower(r.data, content),
          gold: r.data.gold,
        }))
        .sort((a, b) => b.corruption - a.corruption || b.level - a.level || a.name.localeCompare(b.name))
        .slice(0, 25)
        .map((s, i) => ({ rank: i + 1, ...s }));
      return json({ ok: true, standings, rosterSize: rows.length });
    }

    if (req.method === "GET") {
      if (!row) return json({ ok: true, character: null });
      const engine = seed(row.data);
      return json({ ok: true, character: engine.getCharacterView(viewerId), inRun: row.in_run });
    }

    if (req.method !== "POST") return json({ ok: false, message: "Method not allowed" }, 405);

    const command = (await req.json()) as GameCommand;
    if (!command?.type || !ALLOWED.has(command.type)) {
      return json({ ok: false, message: "That is not something you can do here" }, 403);
    }

    // Mid-fight, the character is the resolver's. Letting someone unequip
    // their armour between the fight being read and the result being shown
    // would put the overlay out of step with the character everyone can see.
    if (row?.in_run) {
      return json({ ok: false, message: "You are in a run — try again when it ends." }, 409);
    }

    const engine = seed(row?.data ?? null);
    // `requestedBy` from the TOKEN, overwriting whatever the body claimed.
    const result = engine.dispatch({ ...command, requestedBy: viewerId } as GameCommand);
    if (!result.ok) return json({ ok: false, message: result.message }, 400);

    const updated = engine.roster.get(viewerId);
    if (!updated) return json({ ok: false, message: "No character" }, 404);

    await db("/characters", {
      method: "POST",
      headers: { Prefer: "resolution=merge-duplicates,return=minimal" },
      body: JSON.stringify([
        { id: viewerId, twitch_id: twitchId, data: updated, updated_at: new Date().toISOString() },
      ]),
    });

    // `result.chest` is passed through, and it has to be: opening a chest is
    // the one command whose OUTCOME is not derivable from the character that
    // comes back. The reveal has to name the item at the moment the lid
    // pops, and diffing the bag would have to guess which of two identical
    // instances is the new one. Dropping it here is why the reveal showed a
    // question mark instead of the item.
    return json({
      ok: true,
      message: result.message,
      character: engine.getCharacterView(viewerId),
      ...(result.chest ? { chest: result.chest } : {}),
    });
  } catch (err) {
    console.error(err);
    return json({ ok: false, message: (err as Error).message }, 500);
  }
}

/**
 * An engine holding exactly one character.
 *
 * Per request, and deliberately so: this is a stateless function, two viewers
 * can be served by the same isolate at once, and a shared roster would let one
 * request see another's character. The engine is cheap to build — the
 * expensive part is the content registry, which IS shared because it is
 * read-only.
 */
function seed(character: Character | null): GameEngine {
  const engine = new GameEngine(content, Math.random);
  if (character) engine.roster.hydrate([character]);
  return engine;
}
