/**
 * Bundles the content the loadout's Edge Function needs.
 *
 *   npm run bundle:edge
 *
 * The function validates a viewer's command with the real engine, so it needs
 * the same gear, consumables, shop and balance the game server loads. It does
 * NOT need dungeons or raids — nothing the loadout can do touches a fight —
 * and leaving them out keeps the bundle to the part that matters.
 *
 * A FILE, not a database read. Content changes when the streamer tunes it,
 * which is rarely and deliberately; fetching it per request would add a round
 * trip to every click to track something that moves once a week. Re-run this
 * and redeploy the function after changing gear, prices or balance.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ContentRegistry } from "../src/engine/content/loader.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT = join(ROOT, "content");
const OUT = join(ROOT, "supabase", "functions", "character", "_content.json");

const readDir = (name: string) =>
  readdirSync(join(CONTENT, name))
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(join(CONTENT, name, f), "utf-8")));

const bundle = {
  _comment: "GENERATED by scripts/bundle-edge-content.ts — do not edit. Re-run npm run bundle:edge.",
  gear: readDir("gear"),
  consumables: readDir("consumables"),
  balance: JSON.parse(readFileSync(join(CONTENT, "balance.json"), "utf-8")),
  shop: JSON.parse(readFileSync(join(CONTENT, "shop.json"), "utf-8")),
};

writeFileSync(OUT, `${JSON.stringify(bundle)}
`);

/*
 * The loadout gets the SAME bundle with one difference: the shop arrives with
 * prices already resolved.
 *
 * content/shop.json is a list of ids. The engine wants exactly that — it
 * validates the ids and prices them itself — but the loadout screen wants a
 * ShopView, `{ id, price }[]`, because it has no engine to ask. Against the
 * local game server it gets one: GET /content answers with `shopView()`.
 *
 * Shipping the raw list to the hosted loadout is what made a fully stocked
 * shop render as "Nothing in stock": every entry's `.id` was undefined, so
 * every lookup missed and every row was filtered out. Silent, because an empty
 * shop is a legal shop.
 *
 * The prices come from the loader rather than being recomputed here. The rule
 * is "the item's own value, else its rarity's default, and disabled items drop
 * out" — writing that a second time in this script is how the shop the player
 * sees and the function that takes their gold start disagreeing.
 */
const resolver = new ContentRegistry();
resolver.loadObjects(bundle);
const forLoadout = { ...bundle, shop: resolver.shopView() };

writeFileSync(join(ROOT, "web", "public", "loadout-content.json"), `${JSON.stringify(forLoadout)}
`);
const kb = Math.round(JSON.stringify(bundle).length / 1024);
console.log(`content: ${bundle.gear.length} gear, ${bundle.consumables.length} consumables -> ${kb}KB`);

/**
 * The engine, bundled to one file the function can import.
 *
 * The sources import each other with `.js` specifiers — the TypeScript ESM
 * convention — and Deno resolves those literally, so it would go looking for
 * files that only exist after a compile. Bundling removes the question and
 * leaves the deployed function self-contained, which also makes it start fast.
 *
 * The `node:` imports are left EXTERNAL rather than shimmed. Deno provides all
 * three, and the function never reaches the two that matter: `ContentRegistry`
 * pulls in `node:fs` and `node:path` for its `load*Dir` methods, and the
 * function only ever calls `loadObjects`. Splitting the directory loading into
 * its own module would be tidier and would touch every caller in the server,
 * the simulator and four scripts to remove an import that costs nothing here.
 */
const ENGINE_OUT = join(ROOT, "supabase", "functions", "character", "_engine.js");
// The .cmd shim on Windows is a batch file, which execFileSync cannot launch
// without a shell — hence `shell: true` rather than a second code path.
execFileSync(
  join(ROOT, "node_modules", ".bin", "esbuild"),
  [
    join(ROOT, "src", "engine", "edgeEntry.ts"),
    "--bundle",
    "--format=esm",
    "--platform=neutral",
    "--target=es2022",
    "--external:node:events",
    "--external:node:fs",
    "--external:node:path",
    `--outfile=${ENGINE_OUT}`,
  ],
  { stdio: "inherit", shell: true },
);
const engineKb = Math.round(readFileSync(ENGINE_OUT, "utf-8").length / 1024);
console.log(`engine:  bundled -> ${engineKb}KB`);
