/**
 * Bundles the content the loadout's Edge Function needs.
 *
 *   npm run bundle:edge
 *
 * The function validates a viewer's command with the real engine, so it needs
 * the same gear, consumables, shop and balance the game server loads. It does
 * NOT need dungeons or raids — nothing the loadout can do touches a fight —
 * and leaving them out keeps the bundle to the part that matters.
 *
 * A FILE, not a database read. Content changes when the streamer tunes it,
 * which is rarely and deliberately; fetching it per request would add a round
 * trip to every click to track something that moves once a week. Re-run this
 * and redeploy the function after changing gear, prices or balance.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ContentRegistry } from "../src/engine/content/loader.js";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT = join(ROOT, "content");
const OUT = join(ROOT, "supabase", "functions", "character", "_content.json");

const readDir = (name: string) =>
  readdirSync(join(CONTENT, name))
    .filter((f) => f.endsWith(".json"))
    .map((f) => JSON.parse(readFileSync(join(CONTENT, name, f), "utf-8")));

/**
 * The bestiary index: every body a player can meet, and where.
 *
 * TRIMMED, and built HERE rather than in the browser, for three reasons.
 *
 * Size: content/dungeons is 372KB against a 28KB bundle, and the screen needs
 * a sprite, a name and two numbers per body. Shipping whole dungeon
 * definitions to render a list of portraits is thirteen times the payload for
 * the same page.
 *
 * Secrecy: a dungeon definition carries its loot table with exact drop
 * weights. "What lives here" is a fair thing to look up between runs; "this
 * body drops the axe 3 times in 10" is a different question that nobody asked
 * to have answered, and once it is in the bundle it is public.
 *
 * Duplication: a fight authors a formation per party band and the same
 * watchman appears in most of them, so the raw data is the same body eight
 * times. The dedupe is the same every time it runs, so it runs once at build
 * rather than on every phone that opens the page.
 */
interface BestiaryBody {
  sprite: string;
  name: string;
  hp: number;
  atk: number;
  role?: string;
  /** True when no `weak` formation fields it, i.e. bigger parties only. */
  rare?: boolean;
}

interface BestiaryPlace {
  id: string;
  name: string;
  room?: string;
  bodies: BestiaryBody[];
}

function bodiesOf(formations: Record<string, unknown> | undefined): BestiaryBody[] {
  const seen = new Map<string, BestiaryBody & { bands: string[] }>();
  for (const [band, units] of Object.entries(formations ?? {})) {
    for (const unit of (units as Record<string, never>[] | undefined) ?? []) {
      const u = unit as unknown as {
        sprite: string;
        name?: string;
        role?: string;
        stats?: { hp?: number; atk?: number };
      };
      if (!u?.sprite) continue;
      const name = u.name ?? u.sprite.split("/").pop() ?? u.sprite;
      const key = `${u.sprite}|${name}`;
      const found = seen.get(key);
      if (found) {
        if (!found.bands.includes(band)) found.bands.push(band);
        continue;
      }
      seen.set(key, {
        sprite: u.sprite,
        name,
        hp: u.stats?.hp ?? 0,
        atk: u.stats?.atk ?? 0,
        ...(u.role ? { role: u.role } : {}),
        bands: [band],
      });
    }
  }
  return [...seen.values()].map(({ bands, ...body }) => ({
    ...body,
    ...(bands.includes("weak") ? {} : { rare: true }),
  }));
}

function buildBestiary(): BestiaryPlace[] {
  const out: BestiaryPlace[] = [];

  for (const raw of readDir("dungeons")) {
    const d = raw as { id: string; name: string; formations?: Record<string, unknown> };
    const bodies = bodiesOf(d.formations);
    if (bodies.length) out.push({ id: d.id, name: d.name, bodies });
  }

  for (const raw of readDir("raids")) {
    const r = raw as {
      id: string;
      name: string;
      rooms?: { id: string; name: string; fight?: { formations?: Record<string, unknown> } }[];
      boss?: { id: string; name: string; fight?: { formations?: Record<string, unknown> } };
    };
    // The boss is not in `rooms` - it is never drawn, it is arrived at - so it
    // is appended by hand or the one body everybody looks up is the one
    // missing.
    const rooms = [...(r.rooms ?? []), ...(r.boss ? [r.boss] : [])];
    for (const room of rooms) {
      const bodies = bodiesOf(room.fight?.formations);
      if (bodies.length) out.push({ id: `${r.id}:${room.id}`, name: r.name, room: room.name, bodies });
    }
  }

  return out;
}

const bundle = {
  _comment: "GENERATED by scripts/bundle-edge-content.ts — do not edit. Re-run npm run bundle:edge.",
  gear: readDir("gear"),
  consumables: readDir("consumables"),
  balance: JSON.parse(readFileSync(join(CONTENT, "balance.json"), "utf-8")),
  shop: JSON.parse(readFileSync(join(CONTENT, "shop.json"), "utf-8")),
};

writeFileSync(OUT, `${JSON.stringify(bundle)}
`);

/*
 * The loadout gets the SAME bundle with one difference: the shop arrives with
 * prices already resolved.
 *
 * content/shop.json is a list of ids. The engine wants exactly that — it
 * validates the ids and prices them itself — but the loadout screen wants a
 * ShopView, `{ id, price }[]`, because it has no engine to ask. Against the
 * local game server it gets one: GET /content answers with `shopView()`.
 *
 * Shipping the raw list to the hosted loadout is what made a fully stocked
 * shop render as "Nothing in stock": every entry's `.id` was undefined, so
 * every lookup missed and every row was filtered out. Silent, because an empty
 * shop is a legal shop.
 *
 * The prices come from the loader rather than being recomputed here. The rule
 * is "the item's own value, else its rarity's default, and disabled items drop
 * out" — writing that a second time in this script is how the shop the player
 * sees and the function that takes their gold start disagreeing.
 */
const resolver = new ContentRegistry();
resolver.loadObjects(bundle);
const forLoadout = { ...bundle, shop: resolver.shopView(), bestiary: buildBestiary() };

writeFileSync(join(ROOT, "web", "public", "loadout-content.json"), `${JSON.stringify(forLoadout)}
`);
const kb = Math.round(JSON.stringify(bundle).length / 1024);
const bodies = forLoadout.bestiary.reduce((n, p) => n + p.bodies.length, 0);
console.log(
  `content: ${bundle.gear.length} gear, ${bundle.consumables.length} consumables, ` +
    `${bodies} bestiary bodies in ${forLoadout.bestiary.length} places -> ${kb}KB`,
);

/**
 * The engine, bundled to one file the function can import.
 *
 * The sources import each other with `.js` specifiers — the TypeScript ESM
 * convention — and Deno resolves those literally, so it would go looking for
 * files that only exist after a compile. Bundling removes the question and
 * leaves the deployed function self-contained, which also makes it start fast.
 *
 * The `node:` imports are left EXTERNAL rather than shimmed. Deno provides all
 * three, and the function never reaches the two that matter: `ContentRegistry`
 * pulls in `node:fs` and `node:path` for its `load*Dir` methods, and the
 * function only ever calls `loadObjects`. Splitting the directory loading into
 * its own module would be tidier and would touch every caller in the server,
 * the simulator and four scripts to remove an import that costs nothing here.
 */
const ENGINE_OUT = join(ROOT, "supabase", "functions", "character", "_engine.js");
// The .cmd shim on Windows is a batch file, which execFileSync cannot launch
// without a shell — hence `shell: true` rather than a second code path.
execFileSync(
  join(ROOT, "node_modules", ".bin", "esbuild"),
  [
    join(ROOT, "src", "engine", "edgeEntry.ts"),
    "--bundle",
    "--format=esm",
    "--platform=neutral",
    "--target=es2022",
    "--external:node:events",
    "--external:node:fs",
    "--external:node:path",
    `--outfile=${ENGINE_OUT}`,
  ],
  { stdio: "inherit", shell: true },
);
const engineKb = Math.round(readFileSync(ENGINE_OUT, "utf-8").length / 1024);
console.log(`engine:  bundled -> ${engineKb}KB`);
