"""
Cuts each body's lead fist into its own sprite, for drawing OVER a held weapon.

    python scripts/extract-hands.py

Output: art/sprites/hand/<bodyType>-<tone>.png, mirrored into web/public.

THE PROBLEM THIS SOLVES
-----------------------
A weapon layer drawn above the body sits on top of the hand, so the character
looks like they are presenting the sword rather than gripping it. Drawn below
the body it disappears behind the arm entirely. Neither order is right, because
the truth is in between: the haft passes behind the fingers and in front of the
palm.

The fix is a third layer. The fist is cut out of the body art and re-drawn
ABOVE the weapon, so the weapon is sandwiched — body, weapon, fist. Nothing is
hand-drawn: the pixels are the ones already in the body sprite, so the hand
matches its own skin tone for free and stays correct for all ten bodies.

The crop is measured, not guessed. The lead fist is the rightmost mass of the
figure in its upper-middle band (the pose has it raised and forward), which is
found by scanning rather than hardcoded — the male and female bodies differ in
both size and where the fist sits.
"""

import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
BODY = ROOT / "art" / "sprites" / "body"
OUT = ROOT / "art" / "sprites" / "hand"
PUBLIC = ROOT / "web" / "public" / "art" / "sprites" / "hand"

#: Padding around the detected fist, in px. Generous enough to include the
#: wrist, so the cut-out does not end in a hard edge across the forearm.
PAD = 6

#: How far back from the leading edge the cut-out reaches, as a fraction of the
#: body's width. Enough for the fist and a little wrist; more than this and the
#: forearm comes with it and is re-drawn over the weapon's whole length.
FIST_WIDTH_FRAC = 0.20


def fist_box(img: Image.Image):
    """Bounding box of the lead fist: the rightmost mass at mid-height."""
    w, h = img.size
    px = img.load()
    lo, hi = int(h * 0.25), int(h * 0.60)

    rightmost = []
    for y in range(lo, hi):
        xs = [x for x in range(w) if px[x, y][3] > 128]
        rightmost.append((y, max(xs) if xs else -1))

    edge = max(r[1] for r in rightmost)
    # Rows that reach within 14px of the extreme are part of the same fist,
    # rather than the forearm tapering away behind it.
    rows = [y for y, x in rightmost if x >= edge - 14]
    y0, y1 = min(rows), max(rows)

    # The fist's left edge is a WINDOW from the leading edge, not something to
    # find by following pixels: the fist is joined to the forearm, which is
    # joined to the torso, so walking left through opaque pixels never stops —
    # the first attempt returned a crop as wide as the whole body.
    x0 = edge - round(w * FIST_WIDTH_FRAC)

    return (
        max(0, x0 - PAD),
        max(0, y0 - PAD),
        min(w, edge + 1 + PAD),
        min(h, y1 + 1 + PAD),
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    PUBLIC.mkdir(parents=True, exist_ok=True)

    # One box per BODY TYPE, taken from the reference tone and reused for the
    # rest: the tones are recolours of the same drawing, so a per-tone box would
    # be the same numbers computed ten times — and any disagreement between them
    # would show up as the hand shifting when a player changed skin tone.
    boxes = {}
    for body_type in ("male", "female"):
        ref = BODY / f"{body_type}-fair.png"
        if not ref.exists():
            sys.exit(f"missing {ref}")
        boxes[body_type] = fist_box(Image.open(ref).convert("RGBA"))
        x0, y0, x1, y1 = boxes[body_type]
        print(f"  {body_type}: fist {x1 - x0}x{y1 - y0} at ({x0},{y0})")

    made = 0
    for sprite in sorted(BODY.glob("*.png")):
        body_type = sprite.stem.split("-", 1)[0]
        box = boxes.get(body_type)
        if not box:
            continue
        hand = Image.open(sprite).convert("RGBA").crop(box)
        hand.save(OUT / f"{sprite.stem}.png")
        hand.save(PUBLIC / f"{sprite.stem}.png")
        made += 1

    # The offset is what lets the renderer put the cut-out back exactly where it
    # came from, with no placement tuning: the hand is not positioned, it is
    # RESTORED.
    offsets = {bt: {"x": b[0], "y": b[1]} for bt, b in boxes.items()}
    target = ROOT / "web" / "src" / "handOffsets.ts"
    target.write_text(
        "// GENERATED by scripts/extract-hands.py — do not edit.\n"
        "// Where each body's fist was cut from, in that body sprite's own\n"
        "// pixels. The renderer adds the body's position to put it back.\n"
        "export const HAND_OFFSET: Record<string, { x: number; y: number }> = "
        + repr(offsets).replace("'", '"')
        + ";\n"
    )
    print(f"wrote {made} hand sprites and web/src/handOffsets.ts")


if __name__ == "__main__":
    main()
