// GENERATED by scripts/extract-hands.py — do not edit.
// Where each body's fist was cut from, in that body sprite's own
// pixels. The renderer adds the body's position to put it back.
export const HAND_OFFSET: Record<string, { x: number; y: number }> = {"male": {"x": 195, "y": 138}, "female": {"x": 176, "y": 117}};
